# Generated by Django 5.1.6 on 2025-02-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_customuser_is_email_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="email_verification_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
